In [ ]:
#importing the libraries/packages
# libraries
import numpy as np # used for handling numbers
import pandas as pd # used for handling the dataset

import dtale # used for better stdout of dataframes


from sklearn.impute import SimpleImputer # used for handling missing data
from sklearn.compose import ColumnTransformer # encode categorical data to discrete values
from sklearn.preprocessing import LabelEncoder, OneHotEncoder # used for encoding categorical data
from sklearn.model_selection import train_test_split # used for splitting training and testing data
from sklearn.preprocessing import StandardScaler # used for feature scaling


In [5]:
#to import dataset
import pandas as pd
dataset = pd.read_csv("C:/Users/Admin/Desktop/Ram_Datamininig/DataPreprocessing.csv")
dataset

Region   Age   Income Online Shopper
0   India  49.0  86400.0             No
1  Brazil  32.0  57600.0            Yes
2     USA  35.0  64800.0             No
3  Brazil  43.0  73200.0             No
4     USA  45.0      NaN            Yes
5   India  40.0  69600.0            Yes
6  Brazil   NaN  62400.0             No
7   India  53.0  94800.0            Yes
8     USA  55.0  99600.0             No
9   India  42.0  80400.0            Yes

In [6]:
#Splitting the attributes into independent and dependent attributes
X = dataset.iloc[:, :-1].values # attributes to determine dependent variable / Class
Y = dataset.iloc[:, -1].values # dependent variable / Class

print(X)

[['India' 49.0 86400.0]
 ['Brazil' 32.0 57600.0]
 ['USA' 35.0 64800.0]
 ['Brazil' 43.0 73200.0]
 ['USA' 45.0 nan]
 ['India' 40.0 69600.0]
 ['Brazil' nan 62400.0]
 ['India' 53.0 94800.0]
 ['USA' 55.0 99600.0]
 ['India' 42.0 80400.0]]


In [10]:
#encode categorical data
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
labelencoder_X = LabelEncoder()
X[:, 0] = labelencoder_X.fit_transform(X[:, 0])
ct = ColumnTransformer([("Region", OneHotEncoder(), [0])], remainder = 'passthrough')
X = ct.fit_transform(X)
labelencoder_Y = LabelEncoder()
Y = labelencoder_Y.fit_transform(Y)

In [13]:
#splitting the dataset into training set and test set
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=0)
print(X_train)

[[0.0 1.0 0.0 42.0 80400.0]
 [1.0 0.0 0.0 32.0 57600.0]
 [1.0 0.0 0.0 nan 62400.0]
 [0.0 1.0 0.0 53.0 94800.0]
 [1.0 0.0 0.0 43.0 73200.0]
 [0.0 1.0 0.0 49.0 86400.0]
 [0.0 1.0 0.0 40.0 69600.0]]


In [16]:
#feature scaling
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)
print(X_train)


[[-0.8660254   0.8660254   0.         -0.17494534  0.44897083]
 [ 1.15470054 -1.15470054  0.         -1.67447681 -1.41706417]
 [ 1.15470054 -1.15470054  0.                 nan -1.0242147 ]
 [-0.8660254   0.8660254   0.          1.47453928  1.62751925]
 [ 1.15470054 -1.15470054  0.         -0.02499219 -0.14030338]
 [-0.8660254   0.8660254   0.          0.87472669  0.94003267]
 [-0.8660254   0.8660254   0.         -0.47485163 -0.43494049]]
